
## Assessment 1:

### Assessment 1.1

**Focus**: Basic R, RMarkdown and `tidyverse` data wrangling
1. Setup your Assessment 1 project:

- Create a new Github repo in your Github account.
- Set up this project in your RStudio as shown in class.
- create a RMarkdown document and save it in this project using assessment1.rmd
- Delete parts that you do not need in the RMarkdown template generated by default and copy the tasks below there. You need to leave the `meta data` section and initial R chunk.
- The title of your document should be Assessment 1.1
- The Author is your name and student id
- The date is the date you created he document

You will need to answer each task using the text/graph narration and include R chunks to show how you get them.

2. Create the heading of the first level and call it RMarkdown editing

3. Write 2-3 sentences about RMarkdown (you can google this information or use resources recommended in class - no need to reference)

4. In the above use bold and italics for editing.

5. Review the suggested documentation on how to insert links in the .rmd file and include an in-text link to https://rmarkdown.rstudio.com/lesson-8.html

6. Insert an R chunk and create a variable with this dataset
https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv

The name of the variable should be `fastfood`

7. Display the first 10 rows of the dataset. Use Help to see how you can do this with `head()` function.

8. Display the observations that has more than 1000 calories

9. Save observations with more than 40 in total_fat and more than 80 in total_carb in a new variable called `dont_eat_this`

10. Using the initial dataset variable, display observations from restaurant Mcdonalds

- Save your .rmd file 

- Do a commit in Git tab

- Push in the same tab


### Assessment 1.2

**Focus**: `tidyverse` data wrangling (adv) and `ggplot2`


### Assessment 1.3

**Focus**: factors, strings, dates  

